//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatveiVoevodin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public override string ToString()
        {
            return this.Name;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string Post { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
