//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatveiVoevodin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public override string ToString()
        {
            return this.Name;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int Amount { get; set; }
        public string Production_time { get; set; }
        public string MaterialUsed { get; set; }
        public Nullable<int> StorageId { get; set; }
        public Nullable<int> ReportId { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual Report Report { get; set; }
    }
}
